site_name: Pyte
theme: 'material'

# Github
repo_name: 'GitHub'
repo_url: 'https://github.com/SunDwarf/Pyte'

# Material theme.
extra:
  font:
    text: 'Roboto'
    code: 'BitStream Vera Sans Mono'
  #palette:
    #primary: 'blue'
    #accent: 'green'
  author:
    github: 'SunDwarf'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition